"use client";

import { motion } from "framer-motion";

type Project = {
  title: string;
  kind: string;
  year: string;
  description: string;
  metrics: string[];
  tech: string[];
  github: string;
  live?: string;
  featured?: boolean;
};

const projects: Project[] = [
  {
    title: "civic-philly",
    kind: "Civic data",
    year: "2026",
    description:
      "A real-asset civic tool. 5,000+ housing developments, zoning permits, transit projects, and capital infrastructure investments in Philadelphia, joined against 408 ACS census tracts, 10 council district polygons, 239 RCOs, every council member's contact, 4,212 OPA owners, and 6,400+ L&I displacement signals. Full-text search, public API, RSS, OG, equity overlay, mobile bottom-sheet for organizers at meetings.",
    metrics: ["5,000+ projects", "Public JSON API", "Per-district RSS"],
    tech: ["TypeScript", "Next.js 16", "MapLibre GL", "PostGIS", "Census ACS"],
    github: "https://github.com/c-tonneslan/civic-philly",
    live: "https://civic-philly.vercel.app",
    featured: true,
  },
  {
    title: "septa-live",
    kind: "Transit · Realtime",
    year: "2026",
    description:
      "Live map of every SEPTA mode that publishes realtime data: Regional Rail, BSL, MFL, NHSL, five subway-surface trolleys, Girard, and the suburban trolleys. Hits five SEPTA endpoints through Next.js routes that proxy through Vercel's edge cache. Trains and trolleys reused across polls so they slide instead of flicker.",
    metrics: ["25 lines", "~140 stations", "15s poll, edge-cached"],
    tech: ["TypeScript", "Next.js 16", "Leaflet", "SEPTA APIs"],
    github: "https://github.com/c-tonneslan/septa-live",
    live: "https://septa-live.vercel.app",
  },
  {
    title: "groundwork",
    kind: "Housing · Six cities",
    year: "2026",
    description:
      "Interactive map of 6,500+ affordable-housing projects across NYC, SF, LA, DC, Chicago, and Philly, unified into one Postgres + PostGIS schema. Census-tract rent-burden choropleth, supply-demand gap analysis (PostGIS spatial join), and a stakeholders panel that surfaces the elected representative for any clicked development.",
    metrics: ["6 cities", "6,500+ projects", "PostGIS spatial joins"],
    tech: ["TypeScript", "Next.js", "Postgres", "PostGIS", "Leaflet"],
    github: "https://github.com/c-tonneslan/groundwork",
    live: "https://groundwork-tan.vercel.app",
  },
  {
    title: "marquee",
    kind: "Frontend · Type",
    year: "2026",
    description:
      "A tiny kinetic typography playground. Type a phrase, pick a treatment, watch each glyph animate independently. Five presets: slide, blur, weight (continuous walk of the variable-font weight axis from 200 to 900), jitter, split. The weight preset is the one to look at, you can't fake an axis walk with static cuts.",
    metrics: ["5 presets", "Variable-weight Inter", "40 char limit"],
    tech: ["React 19", "Next.js 16", "Tailwind v4", "Framer Motion"],
    github: "https://github.com/c-tonneslan/marquee",
    live: "https://marquee-pi-bay.vercel.app",
  },
  {
    title: "splitflap",
    kind: "Frontend · Motion",
    year: "2026",
    description:
      "A satisfying Solari-style split-flap departure board for the web. Each cell is a small character drum that ticks one letter at a time until it lands on the target, with a single-pixel hinge across the middle and a small per-cell delay so longer destinations show that mechanical wave. Rows roll forward every few seconds and statuses bump at random. No backend, no audio plugin, just CSS transforms and a charset that steps in order.",
    metrics: ["~55ms per tick", "Pure CSS transforms", "Zero backend"],
    tech: ["React 19", "Next.js 16", "Tailwind v4", "Framer Motion"],
    github: "https://github.com/c-tonneslan/splitflap",
    live: "https://splitflap-chi.vercel.app",
  },
  {
    title: "contestlab",
    kind: "Interview prep · Browser judge",
    year: "2026",
    description:
      "LeetCode-style coding contests in the browser. Four problems per round (easy through hard), 90-minute timer, scoring that decays with elapsed time plus 5-minute wrong-submission penalties. Problems pulled from the Codeforces public API (~9000 rated problems) and generated by Claude for novel slots. Code runs in-browser via Pyodide (Python compiled to WebAssembly), so no rate limits and no backend judge. Built after the public Piston API went whitelist-only.",
    metrics: ["4-problem contests", "In-browser judge (Pyodide)", "AI-generated novel problems"],
    tech: ["TypeScript", "Next.js 16", "Pyodide", "Anthropic Claude", "Monaco"],
    github: "https://github.com/c-tonneslan/contestlab",
    live: "https://contestlab.vercel.app",
  },
  {
    title: "scour",
    kind: "Rust · Parallel grep",
    year: "2026",
    description:
      "A fast, parallel, gitignore-aware recursive grep written from scratch in Rust. A worker pool walks the directory tree across every core; termination uses an atomic counter so whichever worker drops it to zero knows the walk is finished. .gitignore patterns compile to per-rule regexes with deepest-wins resolution. Six modules, around 900 lines, 29 tests.",
    metrics: ["~900 LOC", "Parallel walk", "29 tests"],
    tech: ["Rust", "regex", "crossbeam-channel", "clap"],
    github: "https://github.com/c-tonneslan/scour",
  },
  {
    title: "soda",
    kind: "Go · Open-data CLI",
    year: "2026",
    description:
      "A Go CLI for Socrata-based open data portals. 49 government portals preconfigured. Nine commands including watch for new rows and diff between snapshots. Outputs JSON, NDJSON, CSV, or directly into SQLite — pull --all auto-paginates million-row datasets, upserts on :id.",
    metrics: ["49 portals", "9 commands", "JSON / CSV / SQLite"],
    tech: ["Go 1.25+", "cobra", "modernc.org/sqlite"],
    github: "https://github.com/c-tonneslan/soda",
  },
  {
    title: "convene",
    kind: "Python · Municipal data",
    year: "2026",
    description:
      "Two-platform municipal-data tool: hits Legistar's REST API and HTML-scrapes Granicus's ViewPublisher pages, with 24 US cities preconfigured. Streams events, agenda items, votes, legislation, sponsors, and action history as OCD-shaped JSON, ndjson for jq, or into a 9-table SQLite database.",
    metrics: ["24 cities", "Legistar + Granicus", "OCD-shaped JSON"],
    tech: ["Python 3.11+", "Pydantic 2", "httpx", "SQLite"],
    github: "https://github.com/c-tonneslan/convene",
  },
  {
    title: "littledb",
    kind: "Go · Embedded KV",
    year: "2026",
    description:
      "Tiny embedded key/value store in Go. Single-file ACID with a copy-on-write B+tree, two-meta-page commits, and MVCC-style snapshot reads. Around 1,500 lines. Benchmarks within 5% of bbolt on writes.",
    metrics: ["~1.5k LOC", "Tied with bbolt on writes", "ACID + COW"],
    tech: ["Go", "B+tree", "COW", "CRC32C"],
    github: "https://github.com/c-tonneslan/littledb",
  },
  {
    title: "vouch",
    kind: "Go · Guardrails",
    year: "2026",
    description:
      "A Go CLI for catching AI-code failure modes — silent test deletions, mass test skips, accidental .gitignore additions, fabricated APIs. Runs as a pre-commit hook or in CI. Twelve checks at v1, structured exit codes so it composes with existing tooling.",
    metrics: ["12 checks", "Pre-commit + CI", "Structured exits"],
    tech: ["Go", "AST", "git plumbing"],
    github: "https://github.com/c-tonneslan/vouch",
  },
  {
    title: "fourth-down-audit",
    kind: "Sports · ML",
    year: "2025",
    description:
      "NFL 4th-down decision audit. Trained an XGBoost win-probability model on 300k plays of nflverse pbp; held out 2024 and landed at log-loss 0.465, within 0.3% of nflfastR. Scored every 4th down 2018–2024 with 1,500-iter bootstrap CIs per coach-season.",
    metrics: ["300k plays", "Log-loss 0.465", "1,500-iter bootstrap"],
    tech: ["Python", "XGBoost", "DuckDB", "Next.js"],
    github: "https://github.com/c-tonneslan/fourth-down-audit",
    live: "https://fourth-down-audit.vercel.app",
  },
  {
    title: "flamectl",
    kind: "Go · Profiling",
    year: "2025",
    description:
      "Render a pprof profile as a single-file interactive SVG flamegraph. Takes input from a file, an HTTP URL, or stdin; emits one SVG you can open in any browser. About 600 lines of Go with hand-rolled tree aggregation and SVG layout.",
    metrics: ["~600 LOC", "Single-file SVG", "Hover-to-inspect"],
    tech: ["Go", "pprof", "SVG"],
    github: "https://github.com/c-tonneslan/flamectl",
  },
  {
    title: "agent-eval",
    kind: "Evals · TypeScript",
    year: "2025",
    description:
      "Evaluation framework for agentic LLMs, built from scratch with the Anthropic SDK. 28 tasks across web, code, multistep, and reasoning, scored with a mix of deterministic checks and LLM-as-judge rubrics.",
    metrics: ["28 tasks", "ReAct loop", "95% CIs on results"],
    tech: ["TypeScript", "Anthropic SDK"],
    github: "https://github.com/c-tonneslan/agent-eval",
  },
  {
    title: "airwaves",
    kind: "3D · Radio",
    year: "2025",
    description:
      "Tune into ~5,000 live internet radio stations from a spinning 3D globe. Pick a country, click any marker, hit play. Next.js, Three.js, and the volunteer-run Radio Browser API. The whole thing runs in the browser, no backend.",
    metrics: ["3D globe", "5,000 stations", "Zero backend"],
    tech: ["TypeScript", "Next.js", "Three.js"],
    github: "https://github.com/c-tonneslan/airwaves",
    live: "https://airwaves-steel.vercel.app",
  },
];

function CTAs({ p }: { p: Project }) {
  return (
    <div className="flex items-center gap-3 text-sm">
      {p.live && (
        <a
          href={p.live}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 hover:bg-emerald-500/15 transition"
        >
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse-soft" />
          Live →
        </a>
      )}
      <a
        href={p.github}
        target="_blank"
        rel="noopener noreferrer"
        className="text-muted hover:text-foreground transition border-b border-muted/30 hover:border-foreground pb-0.5"
      >
        Code ↗
      </a>
    </div>
  );
}

export default function Featured() {
  const featured = projects.find((p) => p.featured);
  const rest = projects.filter((p) => !p.featured);

  return (
    <section id="work" className="px-6 lg:px-8 py-24 md:py-32 border-t border-white/6">
      <div className="max-w-6xl mx-auto">
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="grid md:grid-cols-12 gap-6 mb-16"
        >
          <div className="md:col-span-7">
            <p className="text-xs uppercase tracking-widest text-accent mb-4">
              Work
            </p>
            <h2 className="text-4xl md:text-6xl font-semibold tracking-[-0.025em] leading-[1]">
              Twelve
              <br />
              <span className="text-muted">projects.</span>
            </h2>
          </div>
          <p className="md:col-span-5 self-end text-base md:text-lg text-muted leading-relaxed">
            Civic and urban tools, plus developer tooling I built for myself.
            Click anything for code; live demos are marked.
          </p>
        </motion.div>

        {/* Featured project — big card */}
        {featured && (
          <motion.article
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7 }}
            className="relative rounded-2xl border border-white/8 bg-card-bg p-6 md:p-10 mb-8 overflow-hidden"
          >
            <div className="absolute -top-32 -right-32 w-96 h-96 rounded-full bg-[#6bd1ff] opacity-15 blur-[120px]" />
            <div className="relative grid md:grid-cols-12 gap-8 md:gap-10 items-start">
              <div className="md:col-span-7">
                <div className="flex items-center gap-3 mb-4 flex-wrap text-xs">
                  <span className="px-2 py-1 rounded-md bg-accent/15 border border-accent/30 text-accent uppercase tracking-widest font-medium">
                    Featured
                  </span>
                  <span className="text-muted uppercase tracking-widest">
                    {featured.kind}
                  </span>
                  <span className="text-muted font-mono">{featured.year}</span>
                </div>
                <h3 className="text-3xl md:text-5xl font-semibold tracking-[-0.025em] leading-tight mb-4">
                  {featured.title}
                </h3>
                <p className="text-base md:text-lg text-foreground/85 leading-relaxed">
                  {featured.description}
                </p>
              </div>
              <div className="md:col-span-5 space-y-5">
                <div className="grid grid-cols-3 gap-px bg-white/8 rounded-lg overflow-hidden border border-white/8">
                  {featured.metrics.map((m) => (
                    <div key={m} className="bg-card-bg p-3">
                      <p className="text-xs text-foreground/90 leading-tight">
                        {m}
                      </p>
                    </div>
                  ))}
                </div>
                <div>
                  <p className="text-xs text-muted uppercase tracking-widest mb-2">
                    Stack
                  </p>
                  <p className="text-sm font-mono text-foreground/85">
                    {featured.tech.join(" · ")}
                  </p>
                </div>
                <CTAs p={featured} />
              </div>
            </div>
          </motion.article>
        )}

        {/* Rest — two-column grid of compact project cards */}
        <div className="grid md:grid-cols-2 gap-5">
          {rest.map((p, i) => (
            <motion.article
              key={p.title}
              initial={{ opacity: 0, y: 14 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.45, delay: i * 0.04 }}
              className="rounded-xl border border-white/8 bg-card-bg p-6 hover:border-white/15 hover:bg-[#13141a] transition group"
            >
              <div className="flex items-baseline justify-between mb-3 gap-3 flex-wrap">
                <div>
                  <h3 className="text-xl md:text-2xl font-semibold tracking-tight">
                    {p.title}
                  </h3>
                  <p className="text-xs text-muted uppercase tracking-widest mt-1">
                    {p.kind} · {p.year}
                  </p>
                </div>
                <CTAs p={p} />
              </div>
              <p className="text-sm text-foreground/80 leading-relaxed mb-4">
                {p.description}
              </p>
              <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] font-mono text-muted/80 pt-3 border-t border-white/6">
                {p.tech.map((t) => (
                  <span key={t}>{t}</span>
                ))}
              </div>
            </motion.article>
          ))}
        </div>
      </div>
    </section>
  );
}
